name: Chocolatine

on:
  push:
    branches-ignore:
      - 'ga-ignore-*'
  pull_request:
    branches-ignore:
      - 'ga-ignore-*'

env:
  MIRROR_URL: git@github.com:remycnl/Chocolatine.git
  EXECUTABLES: bsq

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Check coding style
        run: |
          check.sh $(pwd) $(pwd);
          if [ -s coding-style-reports.log ];
            then 
              exit 1;
          fi;
          exit 0;

  check_program_compilation:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    needs: [check_coding_style]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Compile program
        timeout-minutes: 2
        run: make
      - name: Clean build artifacts
        run: make clean
      - name: Check executables
        run: |
          IFS=',' read -ra EXECS <<< "$EXECUTABLES"
          for EXEC in "${EXECS[@]}"; do
            if [ ! -x "$EXEC" ]; then
              echo "Executable $EXEC not found or not executable"
              exit 1
            fi
          done

  run_tests:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    needs: [check_program_compilation]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run tests
        timeout-minutes: 2
        run: make tests_run

  push_to_mirror:
    runs-on: ubuntu-latest
    needs: [run_tests]
    if: github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Mirror to repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:remycnl/Chocolatine.git
          ssh_private_key:
            ${{secrets.GIT_SSH_PRIVATE_KEY}}